### PR TITLE
Added TEST.md

### PR DESCRIPTION
**Pull request by kishinmanglani**
* Added TEST.md for demo purposes

### CODE REVIEW

**Comment by byGabyC** [comment]
This looks great!

**Comment by micyukcha** [comment]
Terminal is fun.

**Comment by drellew** [comment]
this looks great

**Comment by daloki** [comment]
Meh.

**Comment by Emersonmcintyre89** [comment]
Awesome!

**Comment by jlp550** [comment]
I'm confused. LOL

**Comment by Seanb06** [comment]
Got it

**Comment by andresbeltran06** [comment]
Finally!

**Comment by marlincohen** [comment]
Hello!

**Comment by slevy486** [comment]
comment

**Comment by slevy486** [comment]
test

**Comment by hahmed2** [comment]
Here

**Pull request closed without merging**
